export type PeruDepartment = {
  name: string;
  provinces: Array<{
    name: string;
    districts: string[];
  }>;
};

export const peruDepartments: PeruDepartment[] = [
  { name: "Amazonas", provinces: [{ name: "Chachapoyas", districts: ["Chachapoyas", "Asunción", "Balsas", "Cheto", "La Jalca", "Levanto", "Magdalena", "Molinopampa", "Montevideo", "Olleros", "Quinjalca", "San Francisco de Daguas", "San Isidro de Maino", "Soloco", "Sonche"] }, { name: "Bagua", districts: ["Bagua", "Aramango", "Copallín", "El Parco", "Imaza", "La Peca"] }, { name: "Utcubamba", districts: ["Bagua Grande", "Cajaruro", "Cumba", "El Milagro", "Jamalca", "Lonya Grande", "Yamón"] }] },
  { name: "Áncash", provinces: [{ name: "Huaraz", districts: ["Huaraz", "Independencia", "Cochabamba", "Colcabamba", "Huanchay", "Jangas", "La Libertad", "Olleros", "Pampas Grande", "Pariacoto", "Pira", "Tarica"] }, { name: "Santa", districts: ["Chimbote", "Nuevo Chimbote", "Cáceres del Perú", "Coishco", "Macate", "Moro", "Nepeña", "Samanco", "Santa"] }, { name: "Huaylas", districts: ["Caraz", "Huallanca", "Huata", "Huaylas", "Mato", "Pamparomás", "Pueblo Libre", "Santa Cruz", "Santo Toribio", "Yuracmarca"] }] },
  { name: "Apurímac", provinces: [{ name: "Abancay", districts: ["Abancay", "Chacoche", "Circa", "Curahuasi", "Huanipaca", "Lambrama", "Pichirhua", "San Pedro de Cachora", "Tamburco"] }, { name: "Andahuaylas", districts: ["Andahuaylas", "Andarapa", "Chiara", "Huancarama", "Huancaray", "Kishuara", "Pacobamba", "Pacucha", "San Jerónimo", "Talavera"] }] },
  { name: "Arequipa", provinces: [{ name: "Arequipa", districts: ["Arequipa", "Alto Selva Alegre", "Cayma", "Cerro Colorado", "Characato", "Chiguata", "Jacobo Hunter", "José Luis Bustamante y Rivero", "La Joya", "Mariano Melgar", "Miraflores", "Mollebaya", "Paucarpata", "Sachaca", "Socabaya", "Tiabaya", "Uchumayo", "Yanahuara", "Yarabamba", "Yura"] }, { name: "Camaná", districts: ["Camaná", "José María Quimper", "Mariano Nicolás Valcárcel", "Mariscal Cáceres", "Nicolás de Piérola", "Ocoña", "Quilca", "Samuel Pastor"] }] },
  { name: "Ayacucho", provinces: [{ name: "Huamanga", districts: ["Ayacucho", "Acocro", "Acos Vinchos", "Carmen Alto", "Chiara", "Jesús Nazareno", "Ocros", "Pacaycasa", "Quinua", "San José de Ticllas", "San Juan Bautista", "Santiago de Pischa", "Socos", "Tambillo", "Vinchos"] }, { name: "Huanta", districts: ["Huanta", "Ayahuanco", "Huamanguilla", "Iguain", "Luricocha", "Santillana", "Sivia", "Llochegua"] }] },
  { name: "Cajamarca", provinces: [{ name: "Cajamarca", districts: ["Cajamarca", "Asunción", "Chetilla", "Cospán", "Encañada", "Jesús", "Llacanora", "Los Baños del Inca", "Magdalena", "Matara", "Namora", "San Juan"] }, { name: "Jaén", districts: ["Jaén", "Bellavista", "Chontalí", "Colasay", "Huabal", "Las Pirias", "Pomahuaca", "Pucará", "Sallique", "San Felipe", "San José del Alto", "Santa Rosa"] }] },
  { name: "Callao", provinces: [{ name: "Callao", districts: ["Callao", "Bellavista", "Carmen de la Legua Reynoso", "La Perla", "La Punta", "Ventanilla", "Mi Perú"] }] },
  { name: "Cusco", provinces: [{ name: "Cusco", districts: ["Cusco", "Ccorca", "Poroy", "San Jerónimo", "San Sebastián", "Santiago", "Saylla", "Wanchaq"] }, { name: "La Convención", districts: ["Santa Ana", "Echarate", "Huayopata", "Maranura", "Ocobamba", "Quellouno", "Kimbiri", "Santa Teresa", "Vilcabamba", "Pichari"] }] },
  { name: "Huancavelica", provinces: [{ name: "Huancavelica", districts: ["Huancavelica", "Acobambilla", "Acoria", "Ascensión", "Conayca", "Cuenca", "Huachocolpa", "Huando", "Izcuchaca", "Laria", "Manta", "Mariscal Cáceres", "Nuevo Occoro", "Palca", "Pilchaca", "Vilca", "Yauli"] }] },
  { name: "Huánuco", provinces: [{ name: "Huánuco", districts: ["Huánuco", "Amarilis", "Chinchao", "Churubamba", "Margos", "Pillco Marca", "Quisqui", "San Francisco de Cayrán", "San Pedro de Chaulán", "Santa María del Valle", "Yarumayo"] }, { name: "Leoncio Prado", districts: ["Rupa-Rupa", "Daniel Alomía Robles", "Hermilio Valdizán", "José Crespo y Castillo", "Luyando", "Mariano Dámaso Beraún"] }] },
  { name: "Ica", provinces: [{ name: "Ica", districts: ["Ica", "La Tinguiña", "Los Aquijes", "Ocucaje", "Pachacútec", "Parcona", "Pueblo Nuevo", "Salas", "San José de los Molinos", "San Juan Bautista", "Santiago", "Subtanjalla", "Tate", "Yauca del Rosario"] }, { name: "Chincha", districts: ["Chincha Alta", "Alto Larán", "Chavín", "Chincha Baja", "El Carmen", "Grocio Prado", "Pueblo Nuevo", "San Juan de Yanac", "San Pedro de Huacarpana", "Sunampe", "Tambo de Mora"] }] },
  { name: "Junín", provinces: [{ name: "Huancayo", districts: ["Huancayo", "Carhuacallanga", "Chacapampa", "Chicche", "Chilca", "Chongos Alto", "Chupuro", "Colca", "Cullhuas", "El Tambo", "Huacrapuquio", "Hualhuas", "Huancán", "Huasicancha", "Huayucachi", "Ingenio", "Pilcomayo", "Pucará", "Quichuay", "Quilcas", "San Agustín", "San Jerónimo de Tunán", "Sapallanga", "Sicaya", "Viques"] }, { name: "Chanchamayo", districts: ["Chanchamayo", "Perené", "Pichanaqui", "San Luis de Shuaro", "San Ramón", "Vitoc"] }] },
  { name: "La Libertad", provinces: [{ name: "Trujillo", districts: ["Trujillo", "El Porvenir", "Florencia de Mora", "Huanchaco", "La Esperanza", "Laredo", "Moche", "Poroto", "Salaverry", "Simbal", "Víctor Larco Herrera"] }, { name: "Ascope", districts: ["Ascope", "Casa Grande", "Chicama", "Chocope", "Magdalena de Cao", "Paiján", "Rázuri", "Santiago de Cao"] }] },
  { name: "Lambayeque", provinces: [{ name: "Chiclayo", districts: ["Chiclayo", "Chongoyape", "Eten", "Eten Puerto", "José Leonardo Ortiz", "La Victoria", "Lagunas", "Monsefú", "Nueva Arica", "Oyotún", "Pátapo", "Picsi", "Pimentel", "Reque", "Santa Rosa", "Tumán"] }, { name: "Lambayeque", districts: ["Lambayeque", "Chóchope", "Íllimo", "Jayanca", "Mochumí", "Mórrope", "Motupe", "Olmos", "Pacora", "Salas", "San José", "Túcume"] }] },
  { name: "Lima", provinces: [{ name: "Lima", districts: ["Lima", "Ancón", "Ate", "Barranco", "Breña", "Carabayllo", "Chaclacayo", "Chorrillos", "Cieneguilla", "Comas", "El Agustino", "Independencia", "Jesús María", "La Molina", "La Victoria", "Lince", "Los Olivos", "Lurigancho", "Lurín", "Magdalena del Mar", "Miraflores", "Pachacámac", "Pucusana", "Pueblo Libre", "Puente Piedra", "Punta Hermosa", "Punta Negra", "Rímac", "San Bartolo", "San Borja", "San Isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martín de Porres", "San Miguel", "Santa Anita", "Santa María del Mar", "Santa Rosa", "Santiago de Surco", "Surquillo", "Villa El Salvador", "Villa María del Triunfo"] }, { name: "Huaral", districts: ["Huaral", "Atavillos Alto", "Atavillos Bajo", "Aucallama", "Chancay", "Ihuarí", "Lampian", "Pacaraos", "San Miguel de Acos", "Santa Cruz de Andamarca", "Sumbilca", "Veintisiete de Noviembre"] }, { name: "Cañete", districts: ["San Vicente de Cañete", "Asia", "Calango", "Cerro Azul", "Chilca", "Coayllo", "Imperial", "Lunahuaná", "Mala", "Nuevo Imperial", "Pacarán", "Quilmaná", "San Antonio", "San Luis", "Santa Cruz de Flores", "Zúñiga"] }] },
  { name: "Loreto", provinces: [{ name: "Maynas", districts: ["Iquitos", "Alto Nanay", "Fernando Lores", "Indiana", "Las Amazonas", "Mazán", "Napo", "Punchana", "Putumayo", "Torres Causana", "Belén", "San Juan Bautista"] }, { name: "Alto Amazonas", districts: ["Yurimaguas", "Balsapuerto", "Jeberos", "Lagunas", "Santa Cruz", "Teniente César López Rojas"] }] },
  { name: "Madre de Dios", provinces: [{ name: "Tambopata", districts: ["Tambopata", "Inambari", "Las Piedras", "Laberinto"] }, { name: "Manu", districts: ["Manu", "Fitzcarrald", "Madre de Dios", "Huepetuhe"] }] },
  { name: "Moquegua", provinces: [{ name: "Mariscal Nieto", districts: ["Moquegua", "Carumas", "Cuchumbaya", "Samegua", "San Cristóbal", "Torata"] }, { name: "Ilo", districts: ["Ilo", "El Algarrobal", "Pacocha"] }] },
  { name: "Pasco", provinces: [{ name: "Pasco", districts: ["Chaupimarca", "Huachón", "Huariaca", "Huayllay", "Ninacaca", "Pallanchacra", "Paucartambo", "San Francisco de Asís de Yarusyacán", "Simón Bolívar", "Ticlacayán", "Tinyahuarco", "Vicco", "Yanacancha"] }, { name: "Oxapampa", districts: ["Oxapampa", "Chontabamba", "Huancabamba", "Palcazú", "Pozuzo", "Puerto Bermúdez", "Villa Rica"] }] },
  { name: "Piura", provinces: [{ name: "Piura", districts: ["Piura", "Castilla", "Catacaos", "Cura Mori", "El Tallán", "La Arena", "La Unión", "Las Lomas", "Tambogrande", "Veintiséis de Octubre"] }, { name: "Sullana", districts: ["Sullana", "Bellavista", "Ignacio Escudero", "Lancones", "Marcavelica", "Miguel Checa", "Querecotillo", "Salitral"] }] },
  { name: "Puno", provinces: [{ name: "Puno", districts: ["Puno", "Acora", "Amantaní", "Atuncolla", "Capachica", "Chucuito", "Coata", "Huata", "Mañazo", "Paucarcolla", "Pichacani", "Platería", "San Antonio", "Tiquillaca", "Vilque"] }, { name: "San Román", districts: ["Juliaca", "Cabana", "Cabanillas", "Caracoto", "San Miguel"] }] },
  { name: "San Martín", provinces: [{ name: "San Martín", districts: ["Tarapoto", "Alberto Leveau", "Cacatachi", "Chazuta", "Chipurana", "El Porvenir", "Huimbayoc", "Juan Guerra", "La Banda de Shilcayo", "Morales", "Papaplaya", "San Antonio", "Sauce", "Shapaja"] }, { name: "Moyobamba", districts: ["Moyobamba", "Calzada", "Habana", "Jepelacio", "Soritor", "Yantaló"] }] },
  { name: "Tacna", provinces: [{ name: "Tacna", districts: ["Tacna", "Alto de la Alianza", "Calana", "Ciudad Nueva", "Inclán", "Pachía", "Palca", "Pocollay", "Sama", "Coronel Gregorio Albarracín Lanchipa"] }, { name: "Jorge Basadre", districts: ["Locumba", "Ilabaya", "Ite"] }] },
  { name: "Tumbes", provinces: [{ name: "Tumbes", districts: ["Tumbes", "Corrales", "La Cruz", "Pampas de Hospital", "San Jacinto", "San Juan de la Virgen"] }, { name: "Zarumilla", districts: ["Zarumilla", "Aguas Verdes", "Matapalo", "Papayal"] }] },
  { name: "Ucayali", provinces: [{ name: "Coronel Portillo", districts: ["Callería", "Campoverde", "Iparía", "Masisea", "Yarinacocha", "Nueva Requena", "Manantay"] }, { name: "Padre Abad", districts: ["Padre Abad", "Irazola", "Curimaná", "Neshuya", "Alexander von Humboldt"] }] },
];

export const getDepartment = (name: string) => peruDepartments.find((item) => item.name === name) || peruDepartments[0];
